[package]
name = "multihash"
description = "Implementation of the multihash format"
repository = "https://github.com/multiformats/rust-multihash"
keywords = ["multihash", "ipfs"]
version = "0.8.1-pre"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/multihash/"

[dependencies]
sha-1 ={ version = "0.8", default-features = false }
sha2 = { version = "0.8", default-features = false }
blake2 = { version = "0.8", default-features = false }
sha3 = { version = "0.8", default-features = false }
digest = "0.8"
integer-encoding = "1.0.5"
failure = "0.1.3"
multihash_derive = { path = "./multihash_derive" }

[dev-dependencies]
hex = "0.3"
