[package]
name = "multihash"
description = "Implementation of the multihash format"
repository = "https://github.com/multiformats/rust-multihash"
keywords = ["multihash", "ipfs"]
version = "0.8.1-pre"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/multihash/"

[dependencies]
sha-1 = "0.8"
sha2 = { version = "0.8", default-features = false }
blake2 = "0.8"
sha3 = "0.8"
digest = "0.8"
generic-array = "0.12"
multihash_derive = { path = "./multihash_derive" }

[dev-dependencies]
hex = "0.3"
